# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspritesuser',
            name='verification_code',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
    ]
