# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 18:37
from __future__ import unicode_literals

import apps.resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(default=None, upload_to=apps.resources.models.upload_resource_path),
            preserve_default=False,
        ),
    ]
